### ISSUE TITLE
Please make this working with Django1.8 and Python3

### ISSUE THREAD

**Issue by karolyi** [dresiu/compressor_requirejs#4]
Hi,

after an unsuccessful try with [django-compressor-requirejs](https://github.com/bpeschier/django-compressor-requirejs), I thought I give a try to your requirejs compiler, but since I use Python3 with the latest Django, your module is failing awfully there.

I started to fix it up locally but I have no time for this, so I have to skip your solution and build my own.

If anytime in the future you'd be fixing your module, please let me know, I'd be happy to give it a try.

Cheers

**Comment by dresiu** [comment]
Hi,
I just introduced some changes, try newest master in your project. It should be compatible with python 3 and tested with django 1.8, compressor 1.6.
I want to produce new pypi package version as soon as possible.
